AllinOneForDummies.Web/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AllinOneForDummies.Web.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

AllinOneForDummies.Web/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AllinOneForDummies.Web.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

AllinOneForDummies.Web/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AllinOneForDummies.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AllinOneForDummies.Web/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AllinOneForDummies.Web.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

AllinOneForDummies.Web/Pages/Planets/Delete.cshtml.cs
using AllinOneForDummies.Core;
using AllinOneForDummies.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AllinOneForDummies.Web.Pages.Planets
{
    public class DeleteModel : PageModel
    {
        private readonly IPlanetData _planetData;
        public Planet Planet { get; set; }

        public DeleteModel(IPlanetData planetData)
        {
            _planetData = planetData;
        }

        public IActionResult OnGet(int planetId)
        {
            Planet = _planetData.GetPlanetById(planetId);
            if (Planet == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        public IActionResult OnPost(int planetId)
        {
            var planet = _planetData.DeletePlanet(planetId);
            _planetData.Commit();
            if (planet == null)
            {
                return RedirectToPage("./NotFound");
            }
            TempData["Message"] = $"{planet.Name} deleted!";
            return RedirectToPage("./List");
        }
    }
}

AllinOneForDummies.Web/Pages/Planets/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AllinOneForDummies.Core;
using AllinOneForDummies.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AllinOneForDummies.Web.Pages.Planets
{
    public class DetailModel : PageModel
    {
        private readonly IPlanetData _planetData;

        [TempData]
        public string Message { get; set; }

        public Planet Planet { get; set; }

        public DetailModel(IPlanetData planetData)
        {
            _planetData = planetData;
        }

        public IActionResult OnGet(int planetId)
        {
            Planet = _planetData.GetPlanetById(planetId);
            if (Planet == null)
            {
                return RedirectToPage("./NotFound");
            }

            return Page();
        }
    }
}

AllinOneForDummies.Web/Pages/Planets/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AllinOneForDummies.Core;
using AllinOneForDummies.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AllinOneForDummies.Web.Pages.Planets
{
    public class EditModel : PageModel
    {
        private readonly IPlanetData _planetData;
        private readonly IHtmlHelper _htmlHelper;

        [BindProperty]
        public Planet Planet { get; set; }
        public IEnumerable<SelectListItem> PlanetTypes { get; set; }

        public EditModel(IPlanetData planetData,
                         IHtmlHelper htmlHelper)
        {
            _planetData = planetData;
            _htmlHelper = htmlHelper;
        }

        public IActionResult OnGet(int? planetId)
        {
            PlanetTypes = _htmlHelper.GetEnumSelectList<PlanetType>();
            if (planetId.HasValue)
            {
                Planet = _planetData.GetPlanetById(planetId.Value);
            }
            else
            {
                Planet = new Planet();
            }
            if (Planet == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        public IActionResult OnPost()
        {            
            if (!ModelState.IsValid)
            {
                PlanetTypes = _htmlHelper.GetEnumSelectList<PlanetType>();
                return Page();
            }
            if (Planet.Id > 0)
            {
                _planetData.UpdatePlanet(Planet);
                TempData["Message"] = "Planet edited!";
            }
            else
            {
                _planetData.AddPlanet(Planet);
                TempData["Message"] = "Planet saved!";
            }
            _planetData.Commit();
            return RedirectToPage("./Detail", new { planetId = Planet.Id });

        }
    }
}

AllinOneForDummies.Web/Pages/Planets/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AllinOneForDummies.Core;
using AllinOneForDummies.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AllinOneForDummies.Web.Pages.Planets
{
    public class ListModel : PageModel
    {
        private readonly IPlanetData _planetData;

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }

        public IEnumerable<Planet> Planets { get; set; }

        public ListModel(IPlanetData planetData)
        {
            _planetData = planetData;
        }

        public void OnGet()
        {
           Planets = _planetData.GetPlanetsByName(SearchTerm);
        }
    }
}

AllinOneForDummies.Web/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AllinOneForDummies.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

AllinOneForDummies.Web/Pages/Stars/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AllinOneForDummies.Web.Pages.Stars
{
    public class ListModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

AllinOneForDummies.Web/Pages/ViewComponents/PlanetCountViewComponent.cs
using AllinOneForDummies.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AllinOneForDummies.Web.Pages.ViewComponents
{
    public class PlanetCountViewComponent : ViewComponent
    {
        private readonly IPlanetData _planetData;

        public PlanetCountViewComponent(IPlanetData planetData)
        {
            _planetData = planetData;
        }

        public IViewComponentResult Invoke()
        {
            var count = _planetData.GetCountOfPlanets();
            return View(count);
        } 
    }
}

AllinOneForDummies.Web/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

AllinOneForDummies.Web/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AllinOneForDummies.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core Razor Pages</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure App Service</a></li>
        </ul>
    </div>
</div>

AllinOneForDummies.Web/Pages/Planets/Delete.cshtml
@page "{planetId:int}"
@model AllinOneForDummies.Web.Pages.Planets.DeleteModel
@{
    ViewData["Title"] = "Delete";
}

<h2>Delete!</h2>
<div class="alert alert-danger">Are you sure you want to delete @Model.Planet.Name?</div>
<form method="post">
    <button type="submit" class="btn btn-danger">Yes!</button>
    <a asp-page="List" class="btn btn-default">Cancel</a>
</form>

AllinOneForDummies.Web/Pages/Planets/Detail.cshtml
@page "{planetId:int}"

@model DetailModel
@{
    ViewData["Title"] = "Detail";
}

<h2>@Model.Planet.Name</h2>

@if (Model.Message != null)
{
    <div class="alert alert-info">@Model.Message</div>
}

<div>
    Id: @Model.Planet.Id
</div>
<div>
    Size: @Model.Planet.Radius
</div>
<div>
    Distance: @Model.Planet.Distance.ToString("N") km
</div>
<div>
    Attractiveness rating: @Model.Planet.AttractivenessRating
</div>
<div>
    Star: @Model.Planet.Star.Name
</div>


<a asp-page="./List" class="btn btn-default">All Planets</a>

AllinOneForDummies.Web/Pages/Planets/Edit.cshtml
@page "{planetId:int?}"

@model AllinOneForDummies.Web.Pages.Planets.EditModel
@{
    ViewData["Title"] = "Edit";
}

<h2>Editing @Model.Planet.Name</h2>
<form method="post">

    <input type="hidden" asp-for="Planet.Id" />
    <div class="form-group">
        <label asp-for="Planet.Name"></label>
        <input asp-for="Planet.Name" class="form-control" />
        <span class="text-danger" asp-validation-for="Planet.Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Planet.Distance"></label>
        <input asp-for="Planet.Distance" class="form-control" />
        <span class="text-danger" asp-validation-for="Planet.Distance"></span>
    </div>
    <div class="form-group">
        <label asp-for="Planet.Radius"></label>
        <input asp-for="Planet.Radius" class="form-control" />
        <span class="text-danger" asp-validation-for="Planet.Radius"></span>
    </div>
    <div class="form-group">
        <label asp-for="Planet.AttractivenessRating"></label>
        <input asp-for="Planet.AttractivenessRating" class="form-control" />
        <span class="text-danger" asp-validation-for="Planet.AttractivenessRating"></span>
    </div>
    <div class="form-group">
        <label asp-for="Planet.PlanetType"></label>
        <select class="form-control" asp-for="Planet.PlanetType"
                asp-items="Model.PlanetTypes">
        </select>

        <span class="text-danger" asp-validation-for="Planet.PlanetType"></span>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/jQueryFixes.js"></script>
}

AllinOneForDummies.Web/Pages/Planets/List.cshtml
@page
@model AllinOneForDummies.Web.Pages.Planets.ListModel
@{
    ViewData["Title"] = "Planets";
}

<h2>Planets</h2>

<form method="get">
    <div class="form-group">
        <div class="input-group">
            <input type="search" class="form-control"
                   asp-for="SearchTerm" />
            <span class="input-group-btn">
                <button class="btn btn-default">
                    <i class="glyphicon glyphicon-search"></i>
                </button>
            </span>
        </div>
    </div>
</form>

@foreach (var planet in Model.Planets)
{
    <partial name="_Summary" model="planet" />

}

<a asp-page="./Edit" class="btn btn-primary">Add planet</a>

AllinOneForDummies.Web/Pages/Planets/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}

<h2>Your planet was not found.</h2>
<a asp-page="./List" class="btn btn-primary">See All planets</a>

AllinOneForDummies.Web/Pages/Planets/_Summary.cshtml
@using AllinOneForDummies.Core
@model Planet

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>@Model.Name</h3>
    </div>
    <div class="panel-body">
        <span>Name: @Model.Name</span>
        <span>Radius: @Model.Radius</span>
        <span>Distance: @Model.Distance.ToString("N") km</span>
        <span>Attractiveness rating: @Model.AttractivenessRating</span>
    </div>
    <div class="panel-footer">
        <a class="btn"
           asp-page="./Detail"
           asp-route-planetId="@Model.Id">
            <i class="glyphicon glyphicon-zoom-in"></i>
        </a>
        <a class="btn"
           asp-page="./Edit"
           asp-route-planetId="@Model.Id">
            <i class="glyphicon glyphicon-edit"></i>
        </a>
        <a class="btn"
           asp-page="./Delete"
           asp-route-planetId="@Model.Id">
            <i class="glyphicon glyphicon-trash"></i>
        </a>
    </div>
</div>

AllinOneForDummies.Web/Pages/Shared/Components/PlanetCount/Default.cshtml
@model int

<div class="well">
    There are @Model planets here. <a asp-page="/Planets/List">See them all!</a>
</div>

AllinOneForDummies.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AllinOneForDummies.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">AllinOneForDummies.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Planets/List">Planets</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <vc:planet-count></vc:planet-count>
            @RenderSection("footer", required: false)
            <p>&copy; 2019 - AllInOneForDummies</p>
            <img src="~/pobrane.jpg" />
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

AllinOneForDummies.Web/Pages/Stars/List.cshtml
@page
@model AllinOneForDummies.Web.Pages.Stars.ListModel
@{
    ViewData["Title"] = "List";
}

<h2>List</h2>